repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.5
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
      - --args=--module
      - --args=--recursive
    - id: terraform_validate
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [--strict]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
    - id: markdownlint
