name: Release Terraform Module

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          release-type: terraform-module
          default-branch: main
          pull-request-title-pattern: "ci: release ${version}"
          token: ${{ secrets.PAT_TOKEN }}
